//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System_Parkir_Application.models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbLocalEntities : DbContext
    {
        public dbLocalEntities()
            : base("name=dbLocalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Parkir> Parkirs { get; set; }
        public virtual DbSet<Pengemudi> Pengemudis { get; set; }
        public virtual DbSet<Tiket> Tikets { get; set; }
    }
}
