//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System_Parkir_Application.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parkir
    {
        public int parkirID { get; set; }
        public Nullable<int> tiketID { get; set; }
        public Nullable<int> pengemudiID { get; set; }
        public string area { get; set; }
        public string lantai { get; set; }
    
        public virtual Pengemudi Pengemudi { get; set; }
        public virtual Tiket Tiket { get; set; }
    }
}
