//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System_Parkir_Application.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tiket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tiket()
        {
            this.Parkirs = new HashSet<Parkir>();
            this.Pengemudis = new HashSet<Pengemudi>();
        }
    
        public int tiketID { get; set; }
        public Nullable<System.DateTime> waktuMasuk { get; set; }
        public Nullable<System.DateTime> waktuKeluar { get; set; }
        public string status { get; set; }
        public Nullable<int> harga { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parkir> Parkirs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pengemudi> Pengemudis { get; set; }
    }
}
